# Generated by Django 4.2 on 2023-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Рубашка", "Рубашка"),
                    ("Штаны", "Штаны"),
                    ("Кофта", "Кофта"),
                    ("Трусы", "Трусы"),
                    ("Кепка", "Кепка"),
                    ("Шорты", "Шорты"),
                    ("Куртка", "Куртка"),
                    ("Шапка", "Шапка"),
                ],
                verbose_name="Категория",
            ),
        ),
    ]
